// Paint types:
// Base: Foundation colors, highly pigmented, good coverage
// Layer: Semi-transparent paints for layering and blending
// Shade: Thin, translucent washes that settle in recesses
// Dry: Heavily pigmented for drybrushing techniques
// Technical: Special effect paints
// Contrast: One-coat paints with built-in shading
// Air: Pre-thinned for airbrush use

// Color data with paint types
window.colors = {
    "Abaddon Black": { hex: "000000", types: ["Base", "Air"] },
    "Averland Sunset": { hex: "fbb81c", types: ["Base", "Air"] },
    "Barak-Nar Burgundy": { hex: "451636", types: ["Base"] },
    "Burgman's glow": { hex: "804c43", types: ["Base"] },
    "Caledor Sky": { hex: "366699", types: ["Base"] },
    "Caliban Green": { hex: "003d15", types: ["Base", "Air"] },
    "Castellan Green": { hex: "264715", types: ["Base", "Air"] },
    "Catachan Flesh": { hex: "804c43", types: ["Base"] },
    "Celestra Grey": { hex: "8ba3a3", types: ["Base"] },
    "Corax White": { hex: "ffffff", types: ["Base"] },
    "Corvus Black": { hex: "171314", types: ["Base", "Air"] },
    "Daemonette Hide": { hex: "655f81", types: ["Base"] },
    "Death Guard Green": { hex: "6d774d", types: ["Base"] },
    "Death Korps Drab": { hex: "3d4539", types: ["Base"] },
    "Deathworld Forest": { hex: "556229", types: ["Base", "Air"] },
    "Dryad Bark": { hex: "2b2a24", types: ["Base"] },
    "Gal Vorbak Red": { hex: "4b213c", types: ["Base"] },
    "Grey Seer": { hex: "a2a5a7", types: ["Base"] },
    "Hobgrot Hide": { hex: "a1812a", types: ["Base"] },
    "Incubi Darkness": { hex: "082e32", types: ["Base"] },
    "Ionrach Skin": { hex: "97a384", types: ["Base"] },
    "Jokaero Orange": { hex: "ed3814", types: ["Base"] },
    "Kantor Blue": { hex: "0de2134e", types: ["Base", "Air"] },
    "Khorne Red": { hex: "650001", types: ["Base", "Air"] },
    "Lupercal Green": { hex: "002c2b", types: ["Base"] },
    "Macragge Blue": { hex: "0f3d7c", types: ["Base", "Air"] },
    "Mechanicus Standard Grey": { hex: "39484a", types: ["Base", "Air"] },
    "Mephiston Red": { hex: "960c09", types: ["Base", "Air"] },
    "Morghast Bone": { hex: "c0a973", types: ["Base"] },
    "Mournfang Brown": { hex: "490f06", types: ["Base", "Air"] },
    "Naggaroth Night": { hex: "3b2b50", types: ["Base"] },
    "Night Lords Blue": { hex: "002b5c", types: ["Base", "Air"] },
    "Nocturne Green": { hex: "162a29", types: ["Base"] },
    "Orruk Flesh": { hex: "8cc276", types: ["Base"] },
    "Phoenician Purple": { hex: "440052", types: ["Base", "Air"] },
    "Rakarth Flesh": { hex: "9c998d", types: ["Base"] },
    "Ratskin Flesh": { hex: "a86648", types: ["Base"] },
    "Rhinox Hide": { hex: "462f30", types: ["Base"] },
    "Screamer Pink": { hex: "7a0e44", types: ["Base"] },
    "Steel Legion Drab": { hex: "584e2d", types: ["Base"] },
    "Stegadon Scale Green": { hex: "06455d", types: ["Base"] },
    "The Fang": { hex: "405b71", types: ["Base", "Air"] },
    "Thondia Brown": { hex: "54302a", types: ["Base"] },
    "Thousand Sons Blue": { hex: "00506f", types: ["Base"] },
    "Waaagh! Flesh": { hex: "0b3b36", types: ["Base"] },
    "Wraithbone": { hex: "dbd1b2", types: ["Base", "Contrast"] },
    "XV-88": { hex: "6c4811", types: ["Base"] },
    "Zandri Dust": { hex: "988e56", types: ["Base", "Air"] },
    
    "Administratum Grey": { hex: "9da099", types: ["Layer"] },
    "Ahriman Blue": { hex: "007c8f", types: ["Layer"] },
    "Alaitoc Blue": { hex: "305688", types: ["Layer"] },
    "Altdorf Guard Blue": { hex: "2a4b9b", types: ["Layer"] },
    "Baharroth Blue": { hex: "64bfce", types: ["Layer"] },
    "Balor Brown": { hex: "925e06", types: ["Layer"] },
    "Baneblade Brown": { hex: "99816b", types: ["Layer"] },
    "Bestigor Flesh": { hex: "d68c50", types: ["Layer"] },
    "Bloodreaver Flesh": { hex: "784d4b", types: ["Layer"] },
    "Blue Horror": { hex: "b0c2d8", types: ["Layer"] },
    "Cadian Fleshtone": { hex: "cb7853", types: ["Layer"] },
    "Calgar Blue": { hex: "456eb4", types: ["Layer"] },
    "Ceramite White": { hex: "ffffff", types: ["Layer"] },
    "Dark Reaper": { hex: "425553", types: ["Layer"] },
    "Dawnstone": { hex: "7a7d74", types: ["Layer"] },
    "Deathclaw Brown": { hex: "b96a52", types: ["Layer"] },
    "Dechala Lilac": { hex: "c0a8d0", types: ["Layer"] },
    "Deepkin Flesh": { hex: "deded2", types: ["Layer"] },
    "Doombull Brown": { hex: "5e0c0a", types: ["Layer"] },
    "Dorn Yellow": { hex: "fff054", types: ["Layer"] },
    "Elysian Green": { hex: "81932f", types: ["Layer"] },
    "Eshin Grey": { hex: "545658", types: ["Layer"] },
    "Evil Sunz Scarlet": { hex: "bf1111", types: ["Layer"] },
    "Fenrisian Grey": { hex: "789dbb", types: ["Layer"] },
    "Fire Dragon Bright": { hex: "f0844b", types: ["Layer"] },
    "Flash Gitz Yellow": { hex: "ffed00", types: ["Layer"] },
    "Flayed One Flesh": { hex: "e8c087", types: ["Layer"] },
    "Fulgrim Pink": { hex: "f4b7d3", types: ["Layer"] },
    "Gauss Blaster Green": { hex: "90c4aa", types: ["Layer"] },
    "Genestealer Purple": { hex: "7c5ba3", types: ["Layer"] },
    "Gorthor Brown": { hex: "c07009", types: ["Layer"] },
    "Hoeth Blue": { hex: "507eb4", types: ["Layer"] },
    "Kabalite Green": { hex: "008560", types: ["Layer"] },
    "Kakophoni Purple": { hex: "9173ae", types: ["Layer"] },
    "Karak Stone": { hex: "c1a068", types: ["Layer"] },
    "Kislev Flesh": { hex: "c9a073", types: ["Layer"] },
    "Krieg Khaki": { hex: "c9c17e", types: ["Layer"] },
    "Loren Forest": { hex: "5c7426", types: ["Layer"] },
    "Lothern Blue": { hex: "3ba1d0", types: ["Layer"] },
    "Lugganath Orange": { hex: "f4a188", types: ["Layer"] },
    "Moot Green": { hex: "56aa2e", types: ["Layer"] },
    "Nurgling Green": { hex: "8fa15f", types: ["Layer"] },
    "Ogryn Camo": { hex: "a9ae40", types: ["Layer"] },
    "Pallid Wych Flesh": { hex: "d6d5c4", types: ["Layer"] },
    "Phalanx Yellow": { hex: "fede32", types: ["Layer"] },
    "Pink Horror": { hex: "96325c", types: ["Layer"] },
    "Russ Grey": { hex: "54758a", types: ["Layer"] },
    "Screaming Skull": { hex: "dad8a6", types: ["Layer"] },
    "Skarsnik Green": { hex: "5f8f67", types: ["Layer"] },
    "Skavenblight Dinge": { hex: "4f4740", types: ["Layer"] },
    "Skrag Brown": { hex: "944b07", types: ["Layer"] },
    "Slaanesh Grey": { hex: "958f9a", types: ["Layer"] },
    "Sons of Horus Green": { hex: "08566a", types: ["Layer"] },
    "Sotek Green": { hex: "0e6875", types: ["Layer"] },
    "Squig Orange": { hex: "af4d3e", types: ["Layer"] },
    "Stormvermin Fur": { hex: "7c7269", types: ["Layer"] },
    "Straken Green": { hex: "6f8515", types: ["Layer"] },
    "Sybarite Green": { hex: "3aa063", types: ["Layer"] },
    "Tallarn Sand": { hex: "aa7d00", types: ["Layer"] },
    "Tau Light Ochre": { hex: "c16f09", types: ["Layer"] },
    "Teclis Blue": { hex: "397bbf", types: ["Layer"] },
    "Temple Guard Blue": { hex: "39998d", types: ["Layer"] },
    "Thunderhawk Blue": { hex: "467379", types: ["Layer"] },
    "Troll Slayer Orange": { hex: "eb641e", types: ["Layer"] },
    "Tuskgor Fur": { hex: "8e3733", types: ["Layer"] },
    "Ulthuan Grey": { hex: "d3e3de", types: ["Layer"] },
    "Ungor Flesh": { hex: "dbac62", types: ["Layer"] },
    "Ushabti Bone": { hex: "c5c180", types: ["Layer"] },
    "Vulkan Green": { hex: "304635", types: ["Layer"] },
    "Warboss Green": { hex: "3c7c54", types: ["Layer"] },
    "Warpfiend Grey": { hex: "757179", types: ["Layer"] },
    "Warpstone Glow": { hex: "277227", types: ["Layer"] },
    "Wazdakka Red": { hex: "8d1207", types: ["Layer"] },
    "White Scar": { hex: "ffffff", types: ["Layer"] },
    "Wild Rider Red": { hex: "e12318", types: ["Layer"] },
    "Word Bearers Red": { hex: "650c12", types: ["Layer"] },
    "Xereus Purple": { hex: "4b225b", types: ["Layer"] },
    "Yriel Yellow": { hex: "ffd900", types: ["Layer"] },
    "Zamesi Desert": { hex: "e0a407", types: ["Layer"] },
    
    // Adding some Contrast paints
    "Black Templar": { hex: "000000", types: ["Contrast"] },
    "Blood Angels Red": { hex: "a91a1d", types: ["Contrast"] },
    "Ultramarines Blue": { hex: "1c3c7c", types: ["Contrast"] },
    "Ork Flesh": { hex: "517d43", types: ["Contrast"] },
    "Space Wolves Grey": { hex: "5b7289", types: ["Contrast"] },
    "Skeleton Horde": { hex: "b6915f", types: ["Contrast"] },
    "Apothecary White": { hex: "e8e8e8", types: ["Contrast"] },
    
    // Adding some Shade paints
    "Nuln Oil": { hex: "1a1a1a", types: ["Shade"] },
    "Agrax Earthshade": { hex: "5c4827", types: ["Shade"] },
    "Reikland Fleshshade": { hex: "aa6e55", types: ["Shade"] },
    "Druchii Violet": { hex: "67537c", types: ["Shade"] },
    "Drakenhof Nightshade": { hex: "243f69", types: ["Shade"] },
    "Biel-Tan Green": { hex: "2c6952", types: ["Shade"] },
    "Seraphim Sepia": { hex: "a77c50", types: ["Shade"] },
    "Casandora Yellow": { hex: "d3a343", types: ["Shade"] }
};


