// Paint types:
// Base: Foundation colors, highly pigmented, good coverage
// Layer: Semi-transparent paints for layering and blending
// Shade: Thin, translucent washes that settle in recesses
// Dry: Heavily pigmented for drybrushing techniques
// Technical: Special effect paints
// Contrast: One-coat paints with built-in shading
// Air: Pre-thinned for airbrush use

// Color data with paint types
window.colors = {
    "Abaddon Black": { hex: "000000", types: ["Base", "Air"] },
    "Averland Sunset": { hex: "fbb81c", types: ["Base", "Air"] },
    "Barak-Nar Burgundy": { hex: "451636", types: ["Base"] },
    "Burgman's glow": { hex: "804c43", types: ["Base"] },
    "Caledor Sky": { hex: "366699", types: ["Base"] },
    "Caliban Green": { hex: "003d15", types: ["Base", "Air"] },
    "Castellan Green": { hex: "264715", types: ["Base", "Air"] },
    "Catachan Flesh": { hex: "804c43", types: ["Base"] },
    "Celestra Grey": { hex: "8ba3a3", types: ["Base"] },
    "Corax White": { hex: "ffffff", types: ["Base"] },
    "Corvus Black": { hex: "171314", types: ["Base", "Air"] },
    "Daemonette Hide": { hex: "655f81", types: ["Base"] },
    "Death Guard Green": { hex: "6d774d", types: ["Base"] },
    "Death Korps Drab": { hex: "3d4539", types: ["Base"] },
    "Deathworld Forest": { hex: "556229", types: ["Base", "Air"] },
    "Dryad Bark": { hex: "2b2a24", types: ["Base"] },
    "Gal Vorbak Red": { hex: "4b213c", types: ["Base"] },
    "Grey Seer": { hex: "a2a5a7", types: ["Base"] },
    "Hobgrot Hide": { hex: "a1812a", types: ["Base"] },
    "Incubi Darkness": { hex: "082e32", types: ["Base"] },
    "Ionrach Skin": { hex: "97a384", types: ["Base"] },
    "Jokaero Orange": { hex: "ed3814", types: ["Base"] },
    "Kantor Blue": { hex: "02134e", types: ["Base", "Air"] },
    "Khorne Red": { hex: "650001", types: ["Base", "Air"] },
    "Lupercal Green": { hex: "002c2b", types: ["Base"] },
    "Macragge Blue": { hex: "0f3d7c", types: ["Base", "Air"] },
    "Mechanicus Standard Grey": { hex: "39484a", types: ["Base", "Air"] },
    "Mephiston Red": { hex: "960c09", types: ["Base", "Air"] },
    "Morghast Bone": { hex: "c0a973", types: ["Base"] },
    "Mournfang Brown": { hex: "490f06", types: ["Base", "Air"] },
    "Naggaroth Night": { hex: "3b2b50", types: ["Base"] },
    "Night Lords Blue": { hex: "002b5c", types: ["Base", "Air"] },
    "Nocturne Green": { hex: "162a29", types: ["Base"] },
    "Orruk Flesh": { hex: "8cc276", types: ["Base"] },
    "Phoenician Purple": { hex: "440052", types: ["Base", "Air"] },
    "Rakarth Flesh": { hex: "9c998d", types: ["Base"] },
    "Ratskin Flesh": { hex: "a86648", types: ["Base"] },
    "Rhinox Hide": { hex: "462f30", types: ["Base"] },
    "Screamer Pink": { hex: "7a0e44", types: ["Base"] },
    "Steel Legion Drab": { hex: "584e2d", types: ["Base"] },
    "Stegadon Scale Green": { hex: "06455d", types: ["Base"] },
    "The Fang": { hex: "405b71", types: ["Base", "Air"] },
    "Thondia Brown": { hex: "54302a", types: ["Base"] },
    "Thousand Sons Blue": { hex: "00506f", types: ["Base"] },
    "Waaagh! Flesh": { hex: "0b3b36", types: ["Base"] },
    "Wraithbone": { hex: "dbd1b2", types: ["Base", "Contrast"] },
    "XV-88": { hex: "6c4811", types: ["Base"] },
    "Zandri Dust": { hex: "988e56", types: ["Base", "Air"] },
    
    "Administratum Grey": { hex: "989C94", types: ["Layer", "Air"] },
    "Ahriman Blue": { hex: "00708A", types: ["Layer"] },
    "Alaitoc Blue": { hex: "2F4F85", types: ["Layer"] },
    "Altdorf Guard Blue": { hex: "2D4696", types: ["Layer"] },
    "Baharroth Blue": { hex: "54BDCA", types: ["Layer"] },
    "Balor Brown": { hex: "875408", types: ["Layer"] },
    "Baneblade Brown": { hex: "8F7C68", types: ["Layer", "Air"] },
    "Bestigor Flesh": { hex: "D08951", types: ["Layer"] },
    "Bloodreaver Flesh": { hex: "6A4848", types: ["Layer"] },
    "Blue Horror": { hex: "9EB5CE", types: ["Layer"] },
    "Cadian Fleshtone": { hex: "C47652", types: ["Layer"] },
    "Calgar Blue": { hex: "2A497F", types: ["Layer"] },
    "Dark Reaper": { hex: "354D4C", types: ["Layer"] },
    "Dawnstone": { hex: "697068", types: ["Layer", "Air"] },
    "Deathclaw Brown": { hex: "AF634F", types: ["Layer"] },
    "Dechala Lilac": { hex: "B598C9", types: ["Layer"] },
    "Deepkin Flesh": { hex: "A9B79F", types: ["Layer"] },
    "Doombull Brown": { hex: "570003", types: ["Layer"] },
    "Dorn Yellow": { hex: "FFF55A", types: ["Layer"] },
    "Elysian Green": { hex: "6B8C37", types: ["Layer", "Air"] },
    "Emperor's children": { hex: "B74073", types: ["Layer"] },
    "Eshin Grey": { hex: "484B4E", types: ["Layer"] },
    "Evil Sunz Scarlet": { hex: "C01411", types: ["Layer", "Air"] },
    "Fenrisian Grey": { hex: "6D94B3", types: ["Layer", "Air"] },
    "Fire Dragon Bright": { hex: "F4874E", types: ["Layer"] },
    "Flash Gitz Yellow": { hex: "FFF300", types: ["Layer", "Air"] },
    "Flayed One Flesh": { hex: "EEC483", types: ["Layer"] },
    "Fulgrim Pink": { hex: "F3ABCA", types: ["Layer"] },
    "Gauss Blaster Green": { hex: "7FC1A5", types: ["Layer"] },
    "Genestealer Purple": { hex: "7658A5", types: ["Layer"] },
    "Gorthor Brown": { hex: "5F463F", types: ["Layer"] },
    "Hoeth Blue": { hex: "4C78AF", types: ["Layer"] },
    "Kabalite Green": { hex: "008962", types: ["Layer"] },
    "Kakophoni Purple": { hex: "8869AE", types: ["Layer"] },
    "Karak Stone": { hex: "B7945C", types: ["Layer"] },
    "Kislev Flesh": { hex: "D1A570", types: ["Layer", "Air"] },
    "Knight-Questor Flesh": { hex: "996563", types: ["Layer"] },
    "Krieg Khaki": { hex: "BCBB7E", types: ["Layer"] },
    "Loren Forest": { hex: "486C25", types: ["Layer"] },
    "Lothern Blue": { hex: "2C9BCC", types: ["Layer", "Air"] },
    "Lugganath Orange": { hex: "F69B82", types: ["Layer"] },
    "Moot Green": { hex: "3DAF44", types: ["Layer", "Air"] },
    "Nurgling Green": { hex: "7E975E", types: ["Layer"] },
    "Ogryn Camo": { hex: "96A648", types: ["Layer", "Air"] },
    "Pallid Wych Flesh": { hex: "CACCBB", types: ["Layer"] },
    "Phalanx Yellow": { hex: "FFE200", types: ["Layer", "Air"] },
    "Pink Horror": { hex: "8E2757", types: ["Layer"] },
    "Russ Grey": { hex: "507085", types: ["Layer", "Air"] },
    "Screaming Skull": { hex: "B9C099", types: ["Layer"] },
    "Skarsnik Green": { hex: "588F6B", types: ["Layer"] },
    "Skavenblight Dinge": { hex: "45413B", types: ["Layer"] },
    "Skrag Brown": { hex: "8B4806", types: ["Layer"] },
    "Slaanesh Grey": { hex: "8B8893", types: ["Layer"] },
    "Sons of Horus Green": { hex: "00545E", types: ["Layer"] },
    "Sotek Green": { hex: "0B6371", types: ["Layer"] },
    "Squig Orange": { hex: "A74D42", types: ["Layer"] },
    "Stormvermin Fur": { hex: "6D655F", types: ["Layer"] },
    "Straken Green": { hex: "597F1C", types: ["Layer"] },
    "Sybarite Green": { hex: "17A166", types: ["Layer"] },
    "Tallarn Sand": { hex: "A07409", types: ["Layer", "Air"] },
    "Tau Light Ochre": { hex: "BC6B10", types: ["Layer"] },
    "Teclis Blue": { hex: "3877BF", types: ["Layer"] },
    "Temple Guard Blue": { hex: "239489", types: ["Layer", "Air"] },
    "Thunderhawk Blue": { hex: "396A70", types: ["Layer"] },
    "Troll Slayer Orange": { hex: "F16C23", types: ["Layer", "Air"] },
    "Tuskgor Fur": { hex: "863231", types: ["Layer"] },
    "Ulthuan Grey": { hex: "C4DDD5", types: ["Layer", "Air"] },
    "Ungor Flesh": { hex: "D1A560", types: ["Layer"] },
    "Ushabti Bone": { hex: "ABA173", types: ["Layer", "Air"] },
    "Vulkan Green": { hex: "223C2E", types: ["Layer"] },
    "Warboss Green": { hex: "317E57", types: ["Layer"] },
    "Warpfiend Grey": { hex: "66656E", types: ["Layer"] },
    "Warpstone Glow": { hex: "0F702A", types: ["Layer"] },
    "Wazdakka Red": { hex: "880804", types: ["Layer"] },
    "White Scar": { hex: "ffffff", types: ["Layer", "Air"] },
    "Wild Rider Red": { hex: "E82E1B", types: ["Layer"] },
    "Word Bearers Red": { hex: "620104", types: ["Layer"] },
    "Xereus Purple": { hex: "47125A", types: ["Layer"] },
    "Yriel Yellow": { hex: "FFD900", types: ["Layer"] },
    "Zamesi Desert": { hex: "D89D1B", types: ["Layer"] },
    
    // Adding some Contrast paints
    "Black Templar": { hex: "000000", types: ["Contrast"] },
    "Blood Angels Red": { hex: "a91a1d", types: ["Contrast"] },
    "Ultramarines Blue": { hex: "1c3c7c", types: ["Contrast"] },
    "Ork Flesh": { hex: "517d43", types: ["Contrast"] },
    "Space Wolves Grey": { hex: "5b7289", types: ["Contrast"] },
    "Skeleton Horde": { hex: "b6915f", types: ["Contrast"] },
    "Apothecary White": { hex: "e8e8e8", types: ["Contrast"] },
    
    // Adding some Shade paints
    "Nuln Oil": { hex: "1a1a1a", types: ["Shade"] },
    "Agrax Earthshade": { hex: "5c4827", types: ["Shade"] },
    "Reikland Fleshshade": { hex: "aa6e55", types: ["Shade"] },
    "Druchii Violet": { hex: "67537c", types: ["Shade"] },
    "Drakenhof Nightshade": { hex: "243f69", types: ["Shade"] },
    "Biel-Tan Green": { hex: "2c6952", types: ["Shade"] },
    "Seraphim Sepia": { hex: "a77c50", types: ["Shade"] },
    "Casandora Yellow": { hex: "d3a343", types: ["Shade"] }
};


